import type { Metadata } from "next";
import { Poppins, Dancing_Script } from "next/font/google";
import "./globals.css";
const poppins = Poppins({ subsets: ["latin"], weight: ["300", "400", "500", "600", "800"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const dancingScript = Dancing_Script({
  subsets: ["latin"],
  weight: ["400", "700"], // Choose weights as needed
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
     
        {children}
       
      </body>
    </html>
  );
}
